name: Compress Images

on:
  push:
    branches:
      - master
    paths:
      - 'images/*.jpg'
      - 'images/*.jpeg'
      - 'images/*.png'
      - 'images/*.webp'

jobs:
  compress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Compress Images
        id: calibre
        uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          jpegQuality: "80"
          compressOnly: true

      - name: Create Pull Request for Compressed Images
        if: steps.calibre.outputs.markdown != ''
        uses: peter-evans/create-pull-request@v4
        with:
          title: Compressed Images
          commit-message: Compressed Images
          body: ${{ steps.calibre.outputs.markdown }}
          branch-suffix: timestamp
