name: Compress Images

on:
  push:
    branches:
      - master

jobs:
  compress:
    runs-on: ubuntu-latest
    name: Optimize Images

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Compress Images
        uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          jpegQuality: "80"
          commit: true
          commitMessage: "ImageOp: Compress images for web optimization"

      - name: Verify no pending changes (Optional)
        run: |
          git diff --exit-code || {
            echo "Warning: Image Action made changes but 'commit: true' might not have worked or there were other changes."
            echo "Please check your repository history."
          }
