name: Compress Images

on:
  pull_request:
    paths:
      - 'images/*.jpg'
      - 'images/*.jpeg'
      - 'images/*.png'
      - 'images/*.webp'

jobs:
  compress:
    runs-on: ubuntu-latest
    name: Optimize Images

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Compress Images
        uses: calibreapp/image-actions@v1
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          jpegQuality: "80"
          commit: true
          commitMessage: "ImageOp: Compress images for web optimization"
