name: Compress Images

on:
  push:
    branches:
      - master

jobs:
  compress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Compress Images
        uses: clydedz/compress-images@v1
        with:
          input-directory: images
          output-directory: dist
          jpg-compression-quality: 60    # Adjust quality (0-100) as needed
          png-compression-quality: 0.5   # Adjust for PNGs (0-1)
          gif-compression-quality: 2     # 1-3

      - name: Replace originals with compressed images
        run: |
          cp -rf dist/* images/

      - name: Commit compressed images
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add images
          git commit -m "Compress all images" || echo "No changes to commit"
          git push
